import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next on every build and rewritten if
    // edited, so linting it only ever produces noise.
    ignores: [".next/**", "node_modules/**", "next-env.d.ts"],
  },
  {
    rules: {
      // The codebase bans `any` outright (plan §11.2); the default warning is
      // too easy to scroll past.
      "@typescript-eslint/no-explicit-any": "error",
    },
  },
];

export default config;
